Repository jonaengs/minigolf-with-friends, pull requests merged in 2021-03, with the labels that each got.

#22 upgrade to junit 5
  build.gradle
  core/src/test/java/TestTest.java
Labels: Config & meta, testing

#24 Setup workflow
  .github/workflows/gradle.yml
  android/build.gradle
  core/src/test/java/TestTest.java
Labels: Config & meta

#30 #10 Graphics (shapes)
  core/src/com/mygdx/minigolf/Game.java
  core/src/com/mygdx/minigolf/controller/EntityFactory.java
  core/src/com/mygdx/minigolf/controller/systems/Graphics.java
  core/src/com/mygdx/minigolf/controller/systems/GraphicsSystem.java
  core/src/com/mygdx/minigolf/controller/systems/LayerComparator.java
  core/src/com/mygdx/minigolf/controller/systems/ObjectiveSystem.java
  core/src/com/mygdx/minigolf/model/components/Graphical.java
  core/src/com/mygdx/minigolf/model/components/Player.java
Labels: Graphics
